### ISSUE TITLE
how to unpack this?

### ISSUE THREAD

**Issue by retratools** [Leaked0/Rose-Obfuscator_xRose#1]
ex. crackme.exe protected with rose obfuscator

**Comment by HideakiAtsuyo** [comment]
> ex. crackme.exe protected with rose obfuscator

Just check the protections code and you will be able to make a deobfuscator for it if you are not a skid :)

https://github.com/Leaked0/Rose-Obfuscator_xRose/tree/main/PRose/Rose/Protections

**Comment by retratools** [comment]
I tried but it didn't work so I opened this issue.

**Comment by HideakiAtsuyo** [comment]
> I tried but it didn't work so I opened this issue.

What didn't work ?

**Comment by retratools** [comment]
> What didn't work ?

i tried write unpacker but it didn't work

**Comment by HideakiAtsuyo** [comment]
> Referen

Well first learn how to use `dnlib` or `AsmResolver` and check some example online if you really have no knowledge about it.
