### ISSUE TITLE
Cant compile project in Visual Studio

### ISSUE THREAD

**Issue by Laka795** [Leaked0/Rose-Obfuscator_xRose#2]
Title

**Comment by HideakiAtsuyo** [comment]
> Title

You need to fix the code.

**Comment by Laka795** [comment]
C# can go kill itself :) 

- Python, java, javascript enthusiast

**Comment by HideakiAtsuyo** [comment]
> C# can go kill itself :)
> 
> * Python, java, javascript enthusiast

Well Python is bad af for me and I don't like Java that much even if it looks like C# but for JS yeah it's good :(
